### ISSUE TITLE
Cache mechanism does not work in `ClassRegistry` and `ProtocolRegistry`

### ISSUE THREAD

**Issue by gebing** [frida/frida-objc-bridge#25]
I found the Cache mechanism of `ClassRegistry` and `ProtocolRegistry` does not work, because if the code of method `findClass` and `findProtocol` do not save the obtained `handle` when not in cache. Below is the code of `ClassRegistry`'s method `findClass`:

```
        function findClass(name) {
            let handle = cachedClasses[name];
            if (handle === undefined)
                handle = api.objc_lookUpClass(Memory.allocUtf8String(name));
            if (handle.isNull())
                return null;
            return new ObjCObject(handle, undefined, true);
        }
```

Another question, why `cachedClasses`/`cachedProtocols` only keep the handle of pointer? Why  not `cachedClasses`/`cachedProtocols` cache `ObjCObject`/`ObjCProtocol` directly?

@oleavr

**Comment by oleavr** [comment]
Thanks, great catch!

The reason we don't cache the wrapper is because the wrapper acts as a cache of what a given class looks like. Because classes can change at runtime, we want users to be able to throw away their wrapper and fetch a fresh one from the registry. This means that we can only cache the handle.

**Comment by oleavr** [comment]
I'm going to fix the cache issue in master as I'm about to cut a release.

**Comment by gebing** [comment]
I made a pull request #26 for fix and enhancement of `ClassRegistry` and `ProtocolRegistry`.
